---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  mssql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
      securityContext:
        fsGroup: 10001
      containers:
      - name: mydb
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
        - name: SA_PASSWORD
          value: "Iiua12345678"
        - name: ACCEPT_EULA
          value: "Y"
        volumeMounts:
        - name: mssqldb
          mountPath: "/var/opt/mssql/data"
      
---          
apiVersion: v1
kind: Service
metadata:
   name: mydb
spec:
  type: LoadBalancer
  selector:
    app: mydb
  ports:
  - port: 1433 
    protocol: TCP
    targetPort: 1433

  
   
    
  
